* Homework10
** Tasks
   - [-] Обеспечьте хранение данных приложения через Firestore.
     - [X] Получение и отображение сохранённых записей
       - [X] FirestoreNotesRepository
       - [X] getNotes()
     - [ ] Добавление новой заметки
   - [X] Внедрить DiffUtil
   - [ ] NoteViewModel
   - [ ] Прибраться в коде

** 08/04/2021
*** 19:24:53
    Прежде всего надо декомпозировать задачи и определиться с тем, что именно
    делать.
*** 19:43:22
    Начало положено. Прежде чем двигаться дальше, надо внедрить DiffUtil.
** 09/04/2021
*** 21:05:41
    Редактирование заметки.
** 10/04/2021
*** 00:15:15
    Кажется никак не сделать это с теми знаниями что пока есть, ну, так чтобы
    оставаться в MVVM.
*** 01:10:08
    Нашёл DataBinding. И надо ещё как-то правильно организовать общение между
    фрагментами с помощью ViewModel.
*** 22:54:26
    Пожалуй с NoteViewModel можно и начать.
** 11/04/2021
*** 12:53:19
    Зафиксировать промежуточные изменения.
*** 16:05:02
    Посмотреть BasicSample из architecture-components-samples.
** 15/04/2021
*** 17:29:58
    По хорошему бы пройтись по коду, и по каждой новой компоненте-модулю
    прописать что он делает. Но надо только позаимствовать кусок отвечающий за
    биндинг для фрагмента заметки.
*** 19:42:08
    Вау, оно работает!
